### ISSUE TITLE
Fix all compilation warnings from cap file build 

### ISSUE THREAD

**Issue by petrs** [JavaCardSpot-dev/smart_card_TLS#4]
[ant:compile] /home/travis/build/JavaCardSpot-dev/smart_card_TLS/applet/src/main/java/applet/credentialtls.java:53: warning: unmappable character for encoding UTF8
[ant:compile]  | UPDATE 2011 - Gilles Bernab�                                                                                 |
[ant:compile]                               ^
[ant:compile] /home/travis/build/JavaCardSpot-dev/smart_card_TLS/applet/src/main/java/applet/eapengine.java:281: warning: [cast] redundant cast to short
[ant:compile] 			ISOException.throwIt((short)((short)SW_VERIFICATION_FAILED | (short)pin.getTriesRemaining()));
[ant:compile] 			                             ^
[ant:compile] /home/travis/build/JavaCardSpot-dev/smart_card_TLS/applet/src/main/java/applet/eapengine.java:774: warning: [cast] redundant cast to short
[ant:compile] 					ISOException.throwIt((short)((short)SW_PIN_VERIFICATION_REQUIRED | (short)UserPin.getTriesRemaining()));
[ant:compile] 					                             ^
[ant:compile] /home/travis/build/JavaCardSpot-dev/smart_card_TLS/applet/src/main/java/applet/eapengine.java:832: warning: [cast] redundant cast to short
[ant:compile] 					ISOException.throwIt((short)((short)SW_PIN_VERIFICATION_REQUIRED | (short)UserPin.getTriesRemaining()));
[ant:compile] 					                             ^
[ant:compile] /home/travis/build/JavaCardSpot-dev/smart_card_TLS/applet/src/main/java/applet/eapengine.java:843: warning: [cast] redundant cast to short
[ant:compile] 					ISOException.throwIt((short)((short)SW_PIN_VERIFICATION_REQUIRED | (short)UserPin.getTriesRemaining()));
[ant:compile] 					                             ^
[ant:compile] /home/travis/build/JavaCardSpot-dev/smart_card_TLS/applet/src/main/java/applet/eapengine.java:877: warning: [cast] redundant cast to short
[ant:compile] 					ISOException.throwIt((short)((short)SW_PIN_VERIFICATION_REQUIRED | (short)UserPin.getTriesRemaining()));
[ant:compile] 					                             ^
[ant:compile] /home/travis/build/JavaCardSpot-dev/smart_card_TLS/applet/src/main/java/applet/eapengine.java:879: warning: [cast] redundant cast to short
[ant:compile] 				len = Process_EAP(buffer,(short)len,apdu);
[ant:compile] 				                         ^
[ant:compile] /home/travis/build/JavaCardSpot-dev/smart_card_TLS/applet/src/main/java/applet/eapengine.java:902: warning: [cast] redundant cast to short
[ant:compile] 					ISOException.throwIt((short)((short)SW_PIN_VERIFICATION_REQUIRED | (short)OperatorPin.getTriesRemaining()));
[ant:compile] 					                             ^
[ant:compile] /home/travis/build/JavaCardSpot-dev/smart_card_TLS/applet/src/main/java/applet/eapengine.java:917: warning: [cast] redundant cast to short
[ant:compile] 					ISOException.throwIt((short)((short)SW_PIN_VERIFICATION_REQUIRED | (short)OperatorPin.getTriesRemaining()));
[ant:compile] 					                             ^
[ant:compile] /home/travis/build/JavaCardSpot-dev/smart_card_TLS/applet/src/main/java/applet/eapengine.java:920: warning: [cast] redundant cast to short
[ant:compile] 				if ((adrc <0) || (adrc >= (short)NVR_Size)) 
[ant:compile] 				                          ^
[ant:compile] /home/travis/build/JavaCardSpot-dev/smart_card_TLS/applet/src/main/java/applet/eapengine.java:922: warning: [cast] redundant cast to short
[ant:compile] 				else if ((short)(adrc  + len) > (short)NVR_Size) ISOException.throwIt(ISO7816.SW_WRONG_LENGTH) ;
[ant:compile] 				                                ^
[ant:compile] /home/travis/build/JavaCardSpot-dev/smart_card_TLS/applet/src/main/java/applet/eapengine.java:931: warning: [cast] redundant cast to short
[ant:compile] 					ISOException.throwIt((short)((short)SW_PIN_VERIFICATION_REQUIRED | (short)UserPin.getTriesRemaining()));
[ant:compile] 					                             ^
[ant:compile] /home/travis/build/JavaCardSpot-dev/smart_card_TLS/applet/src/main/java/applet/eapengine.java:951: warning: [cast] redundant cast to short
[ant:compile] 			ISOException.throwIt((short)SW_FETCH);
[ant:compile] 			                     ^
[ant:compile] /home/travis/build/JavaCardSpot-dev/smart_card_TLS/applet/src/main/java/applet/eapengine.java:966: warning: [cast] redundant cast to short
[ant:compile] 		ISOException.throwIt((short)((short)SW_FETCH | (short)((short)0xFF & len)));
[ant:compile] 		                             ^
[ant:compile] /home/travis/build/JavaCardSpot-dev/smart_card_TLS/applet/src/main/java/applet/methodtls.java:325: warning: [cast] redundant cast to short
[ant:compile] 				Util.setShort(HH,(short)(offset+8),(short)len);
[ant:compile] 				                                   ^
[ant:compile] /home/travis/build/JavaCardSpot-dev/smart_card_TLS/applet/src/main/java/applet/methodtls.java:331: warning: [cast] redundant cast to short
[ant:compile] 				Util.setShort(HH,(short)(offset+4),(short)len);
[ant:compile] 				                                   ^
[ant:compile] /home/travis/build/JavaCardSpot-dev/smart_card_TLS/applet/src/main/java/applet/methodtls.java:390: warning: [cast] redundant cast to byte
[ant:compile] 				len = Util.makeShort((byte)0x00,(byte) buffer[4]);
[ant:compile] 				                                ^
[ant:compile] /home/travis/build/JavaCardSpot-dev/smart_card_TLS/applet/src/main/java/applet/methodtls.java:391: warning: [cast] redundant cast to short
[ant:compile] 				rnd.generateData(buffer,(short)0,(short)len);
[ant:compile] 				                                 ^
[ant:compile] /home/travis/build/JavaCardSpot-dev/smart_card_TLS/applet/src/main/java/applet/methodtls.java:392: warning: [cast] redundant cast to short
[ant:compile] 				apdu.setOutgoingAndSend((short)0,(short)len); 
[ant:compile] 				                                 ^
[ant:compile] /home/travis/build/JavaCardSpot-dev/smart_card_TLS/applet/src/main/java/applet/methodtls.java:875: warning: [cast] redundant cast to short
[ant:compile] 					doFinal(md5,heap,(short)(heap_offset+10),(short)(heap_ptr-heap_offset-10+16),hash,(short)(hash_off));
[ant:compile] 					                                                                                  ^
[ant:compile] /home/travis/build/JavaCardSpot-dev/smart_card_TLS/applet/src/main/java/applet/methodtls.java:925: warning: [cast] redundant cast to short
[ant:compile] 					cipherAES.init(clientAESKey, Cipher.MODE_ENCRYPT, key_block, (short) (IV_offset), block_length);
[ant:compile] 					                                                             ^
[ant:compile] /home/travis/build/JavaCardSpot-dev/smart_card_TLS/applet/src/main/java/applet/methodtls.java:927: warning: [cast] redundant cast to short
[ant:compile] 					Util.arrayCopyNonAtomic(heap, (short)(heap_ptr+16+HASH_SIZE+padding_length-block_length), key_block, (short)IV_offset, block_length);
[ant:compile] 					                                                                                                     ^
[ant:compile] /home/travis/build/JavaCardSpot-dev/smart_card_TLS/applet/src/main/java/applet/methodtls.java:1081: warning: [cast] redundant cast to short
[ant:compile] 					doFinal(md5,heap,(short)(heap_offset+10),(short)(len3-heap_offset-10),hash,(short)(hash_off));
[ant:compile] 					                                                                           ^
[ant:compile] /home/travis/build/JavaCardSpot-dev/smart_card_TLS/applet/src/main/java/applet/methodtls.java:1176: warning: [cast] redundant cast to short
[ant:compile] 						cipherAES.doFinal(heap, heap_ptr, (short)(len), heap, heap_ptr);
[ant:compile] 						                                  ^
[ant:compile] /home/travis/build/JavaCardSpot-dev/smart_card_TLS/applet/src/main/java/applet/methodtls.java:1180: warning: [cast] redundant cast to short
[ant:compile] 						if (!RecordLayerHMAC((byte)23,(short)(len),numct_server,true))
[ant:compile] 						                              ^
[ant:compile] /home/travis/build/JavaCardSpot-dev/smart_card_TLS/applet/src/main/java/applet/methodtls.java:1185: warning: [cast] redundant cast to short
[ant:compile] 						heap_ptr = (short)((short)heap_ptr+(short)len);
[ant:compile] 						                   ^
[ant:compile] /home/travis/build/JavaCardSpot-dev/smart_card_TLS/applet/src/main/java/applet/methodtls.java:1185: warning: [cast] redundant cast to short
[ant:compile] 						heap_ptr = (short)((short)heap_ptr+(short)len);
[ant:compile] 						                                   ^
[ant:compile] /home/travis/build/JavaCardSpot-dev/smart_card_TLS/applet/src/main/java/applet/methodtls.java:1201: warning: [cast] redundant cast to short
[ant:compile] 						heap_ptr= (short)(old_ptr); 
[ant:compile] 						          ^
[ant:compile] /home/travis/build/JavaCardSpot-dev/smart_card_TLS/applet/src/main/java/applet/methodtls.java:1213: warning: [cast] redundant cast to short
[ant:compile] 						MakeRecordHeader(heap,(short)((short)heap_ptr-(short)5),(byte)23,(short)(len+HASH_SIZE+padding_length));
[ant:compile] 						                              ^
[ant:compile] /home/travis/build/JavaCardSpot-dev/smart_card_TLS/applet/src/main/java/applet/methodtls.java:1214: warning: [cast] redundant cast to short
[ant:compile] 						RecordLayerHMAC((byte)23,(short)len,numct_client,false);
[ant:compile] 						                         ^
[ant:compile] /home/travis/build/JavaCardSpot-dev/smart_card_TLS/applet/src/main/java/applet/methodtls.java:1217: warning: [cast] redundant cast to short
[ant:compile] 						cipherAES.init(clientAESKey, Cipher.MODE_ENCRYPT, key_block, (short) (IV_offset), block_length);
[ant:compile] 						                                                             ^
[ant:compile] /home/travis/build/JavaCardSpot-dev/smart_card_TLS/applet/src/main/java/applet/methodtls.java:1219: warning: [cast] redundant cast to short
[ant:compile] 						Util.arrayCopyNonAtomic(heap, (short)(heap_ptr+len+HASH_SIZE+padding_length-block_length), key_block, (short)IV_offset, block_length);
[ant:compile] 						                                                                                                      ^
[ant:compile] /home/travis/build/JavaCardSpot-dev/smart_card_TLS/applet/src/main/java/applet/methodtls.java:1233: warning: [cast] redundant cast to short
[ant:compile] 		for(i=(short)(offset+length-19); i>(short)offset; i--)
[ant:compile] 		                                   ^
[ant:compile] /home/travis/build/JavaCardSpot-dev/smart_card_TLS/applet/src/main/java/applet/methodtls.java:1235: warning: [cast] redundant cast to short
[ant:compile] 			if(Util.arrayCompare(buffer,(short)(i),form_pass,(short)(0),(short)(form_pass.length))==(short)0)
[ant:compile] 			                            ^
[ant:compile] /home/travis/build/JavaCardSpot-dev/smart_card_TLS/applet/src/main/java/applet/methodtls.java:1238: warning: [cast] redundant cast to short
[ant:compile] 			if(Util.arrayCompare(buffer,(short)(i),form_user,(short)(0),(short)(form_user.length))==(short)0)
[ant:compile] 			                            ^
[ant:compile] /home/travis/build/JavaCardSpot-dev/smart_card_TLS/applet/src/main/java/applet/methodtls.java:1467: warning: [cast] redundant cast to short
[ant:compile] 			P_Hash,(short)P_Hash_off);
[ant:compile] 			       ^
[ant:compile] /home/travis/build/JavaCardSpot-dev/smart_card_TLS/applet/src/main/java/applet/methodtls.java:1475: warning: [cast] redundant cast to short
[ant:compile] 				P_Hash,(short)P_Hash_off,P_Hash_len,sha,
[ant:compile] 				       ^
[ant:compile] /home/travis/build/JavaCardSpot-dev/smart_card_TLS/applet/src/main/java/applet/methodtls.java:1476: warning: [cast] redundant cast to short
[ant:compile] 			P,(short)P_off);
[ant:compile] 			  ^
[ant:compile] /home/travis/build/JavaCardSpot-dev/smart_card_TLS/applet/src/main/java/applet/methodtls.java:1479: warning: [cast] redundant cast to short
[ant:compile] 				P_Hash,(short)P_Hash_off,(short)20,sha,
[ant:compile] 				       ^
[ant:compile] /home/travis/build/JavaCardSpot-dev/smart_card_TLS/applet/src/main/java/applet/methodtls.java:1480: warning: [cast] redundant cast to short
[ant:compile] 				P_Hash,(short)P_Hash_off);
[ant:compile] 				       ^
[ant:compile] /home/travis/build/JavaCardSpot-dev/smart_card_TLS/applet/src/main/java/applet/methodtls.java:1521: warning: [cast] redundant cast to short
[ant:compile] 		if (lk > (short)BLOCKSIZE) 
[ant:compile] 		         ^
[ant:compile] /home/travis/build/JavaCardSpot-dev/smart_card_TLS/applet/src/main/java/applet/methodtls.java:1797: warning: [cast] redundant cast to short
[ant:compile] 	   		len = Util.arrayCompare(con,con_off,con,(short)(con_off+len),(short)len) ;
[ant:compile] 	   		                                                             ^
[ant:compile] /home/travis/build/JavaCardSpot-dev/smart_card_TLS/applet/src/main/java/applet/methodtls.java:408: warning: [fallthrough] possible fall-through into case
[ant:compile] 			case FCT_PUBLIC_ENCRYPT:
[ant:compile] 			^
[ant:compile] /home/travis/build/JavaCardSpot-dev/smart_card_TLS/applet/src/main/java/applet/methodtls.java:443: warning: [fallthrough] possible fall-through into case
[ant:compile] 			case FCT_PRIVATE_DECRYPT:
[ant:compile] 			^
[ant:compile] /home/travis/build/JavaCardSpot-dev/smart_card_TLS/applet/src/main/java/applet/methodtls.java:707: warning: [fallthrough] possible fall-through into case
[ant:compile] 				case (byte)50 :
[ant:compile] 				^
[ant:compile] /home/travis/build/JavaCardSpot-dev/smart_card_TLS/applet/src/main/java/applet/methodtls.java:776: warning: [fallthrough] possible fall-through into case
[ant:compile] 				case (byte)51 :
[ant:compile] 				^
[ant:compile] /home/travis/build/JavaCardSpot-dev/smart_card_TLS/applet/src/main/java/applet/methodtls.java:784: warning: [fallthrough] possible fall-through into case
[ant:compile] 				case (byte)52 :
[ant:compile] 				^
[ant:compile] /home/travis/build/JavaCardSpot-dev/smart_card_TLS/applet/src/main/java/applet/methodtls.java:794: warning: [fallthrough] possible fall-through into case
[ant:compile] 				case (byte)53 :
[ant:compile] 				^
[ant:compile] /home/travis/build/JavaCardSpot-dev/smart_card_TLS/applet/src/main/java/applet/methodtls.java:814: warning: [fallthrough] possible fall-through into case
[ant:compile] 				case (byte)54 :
[ant:compile] 				^
[ant:compile] /home/travis/build/JavaCardSpot-dev/smart_card_TLS/applet/src/main/java/applet/methodtls.java:839: warning: [fallthrough] possible fall-through into case
[ant:compile] 				case (byte)55 :
[ant:compile] 				^
[ant:compile] /home/travis/build/JavaCardSpot-dev/smart_card_TLS/applet/src/main/java/applet/methodtls.java:870: warning: [fallthrough] possible fall-through into case
[ant:compile] 				case (byte)56 :
[ant:compile] 				^
[ant:compile] /home/travis/build/JavaCardSpot-dev/smart_card_TLS/applet/src/main/java/applet/methodtls.java:881: warning: [fallthrough] possible fall-through into case
[ant:compile] 				case (byte)57 :
[ant:compile] 				^
[ant:compile] /home/travis/build/JavaCardSpot-dev/smart_card_TLS/applet/src/main/java/applet/methodtls.java:911: warning: [fallthrough] possible fall-through into case
[ant:compile] 				case (byte)58 :
[ant:compile] 				^
[ant:compile] /home/travis/build/JavaCardSpot-dev/smart_card_TLS/applet/src/main/java/applet/methodtls.java:920: warning: [fallthrough] possible fall-through into case
[ant:compile] 				case (byte)59 :
[ant:compile] 				^
[ant:compile] /home/travis/build/JavaCardSpot-dev/smart_card_TLS/applet/src/main/java/applet/methodtls.java:986: warning: [fallthrough] possible fall-through into case
[ant:compile] 				case (byte)81 :
[ant:compile] 				^
[ant:compile] /home/travis/build/JavaCardSpot-dev/smart_card_TLS/applet/src/main/java/applet/methodtls.java:1001: warning: [fallthrough] possible fall-through into case
[ant:compile] 				case (byte)82 :
[ant:compile] 				^
[ant:compile] /home/travis/build/JavaCardSpot-dev/smart_card_TLS/applet/src/main/java/applet/methodtls.java:1016: warning: [fallthrough] possible fall-through into case
[ant:compile] 				case (byte)83 :
[ant:compile] 				^
[ant:compile] /home/travis/build/JavaCardSpot-dev/smart_card_TLS/applet/src/main/java/applet/methodtls.java:1038: warning: [fallthrough] possible fall-through into case
[ant:compile] 				case (byte)84 :
[ant:compile] 				^
[ant:compile] /home/travis/build/JavaCardSpot-dev/smart_card_TLS/applet/src/main/java/applet/methodtls.java:1113: warning: [fallthrough] possible fall-through into case
[ant:compile] 				case (byte)91 :
[ant:compile] 				^
[ant:compile] /home/travis/build/JavaCardSpot-dev/smart_card_TLS/applet/src/main/java/applet/methodtls.java:1126: warning: [fallthrough] possible fall-through into case
[ant:compile] 				case (byte)92 :
[ant:compile] 				^
[ant:compile] 60 warnings

**Comment by coolsujit** [comment]
Sir,
I have removed "Redundant cast to short" warnings and now the warnings are reduced from 60 to 19. However, the remaining warnings of "possible fall-through in to case" cannot be removed now, as it looks like that the programmer wants this fall-through as per his design of the code. Also to remove these warnings I need to look deep into the code to understand what is happening. I will keep in mind about these remaining warnings and will try to remove them but at this juncture not possible to do so. 
Regards.

**Comment by coolsujit** [comment]
Readme.md also updated with notice and Second Semester text.

**Comment by coolsujit** [comment]
[ant:verify] Mar 15, 2018 6:12:47 PM  
[ant:verify] INFO: Verifying CAP file /home/travis/build/JavaCardSpot-dev/smart_card_TLS/applet/build/javacard/applet.cap
[ant:verify] Mar 15, 2018 6:12:47 PM  
[ant:verify] INFO: Verification completed with 0 warnings and 0 errors.

Sir, 
All warnings which are not due to implementation requirements are removed and remaining warnings which are due to implementation requirements (e.g. fallthrough in case statements) has been suppressed. Now there are no warnings or error in the build. 
As all warnings are removed, let me know if i can close this issue.

**Comment by petrs** [comment]
Thnak you, its clear now
